In [1]:
import numpy as np
import pandas as pd

## Series is 1D and DataFrame are 2D objects

- but why?
- and what exactly is index?

#### 1. Series vs DataFrame
- Series = 1D  
  Only one axis (index)  
  Think: single column  

- DataFrame = 2D  
  Two axes (index and columns)  
  Think: table (rows × columns)  

#### 2. Index
- Index = labels of rows  
- Used to identify and access data  
- It is not the actual data  

#### 3. One-line memory trick
- Series = index + values  
- DataFrame = index + columns + values  

#### 4. Most important idea
- DataFrame = collection of Series (columns)

In [2]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [3]:
a[('cse',2022)]

np.int64(4)

In [7]:
# the problem?

# a['cse']

# error :---> KeyError: 'cse'

# we can not access data based on the branch

In [8]:
# the solution--> multiindex series (also known as Hierarchical Indexing)
# multiple index levels within a single index

### How to create multiIndex objects

In [11]:
# 1. pd.MultiIndex.from_tuples()

index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [12]:
multiindex.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [16]:
multiindex.levels[0]

Index(['cse', 'ece'], dtype='object')

In [17]:
multiindex.levels[0][0]

'cse'

In [18]:
multiindex.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [19]:
# 2. pd.MultiIndex.from_product()

pd.MultiIndex.from_product([['cse', 'ece'], [2019, 2020, 2021, 2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [23]:
# creating a series with multiindex objects

s = pd.Series([1,2,3,4,5,6,7,8], index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [24]:
# how to fetch items from such a series

s[('cse',2022)]

np.int64(4)

In [25]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

### unstack and stack

In [26]:
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [28]:
# unstack
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [29]:
# stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

#### Stack
- Converts **columns into rows**
- Makes DataFrame more "vertical"
- Result is usually a **Series** (or multi-index DataFrame)

```
Example:
      A   B
0    10  40
1    20  50

After stack:
0  A    10
   B    40
1  A    20
   B    50
```

#### Unstack
- Converts **rows into columns**
- Makes data more "horizontal"
- Opposite of stack

```
Example (above stacked data):

0  A    10
   B    40
1  A    20
   B    50

After unstack:
      A   B
0    10  40
1    20  50
```

#### One-line memory trick
- stack = columns to rows  
- unstack = rows to columns

### Why use MultiIndex, stack, and unstack?

You’re right to question this. If DataFrame already works, why complicate it?

#### 1. Because real data is not always flat
Normal DataFrame works when data is simple.

But sometimes data has **multiple dimensions**:
- sales by (year, city)
- marks by (student, subject)
- IPL data by (match, player)

In these cases, one index is not enough.

So we use **MultiIndex** to represent hierarchy.

---

#### 2. MultiIndex = better structure (not complexity)
Instead of repeating values:

Without MultiIndex:
```
Student   Subject   Marks
A         Math      90
A         Science   85
```

With MultiIndex:
```
          Marks
A   Math     90
    Science  85
```

Cleaner and more structured.

---

#### 3. Why stack and unstack?

Because different operations need different shapes.

- Some operations work better in **wide format** (columns)
- Some work better in **long format** (rows)

So we reshape data when needed.

---

#### 4. Practical use cases

1. **GroupBy results**
   After groupby, you often get MultiIndex  
   You use unstack to make it readable

2. **Pivot tables**
   Pivot creates MultiIndex  
   Unstack helps reshape it

3. **Data analysis**
   Stack helps convert wide data into long format for analysis

---

#### 5. Simple intuition

- MultiIndex = storing extra dimensions
- stack = compress columns into rows
- unstack = expand rows into columns

---

#### 6. One-line crux
- We use them to **reshape data depending on what operation we want to perform**

In [31]:
# We use MultiIndex when one index is not enough to represent the data properly.

# It lets us store multiple levels like (year, city) or (student, subject) in a clean structured way instead of repeating values.

# In short, MultiIndex helps represent complex, multi-dimensional data inside a DataFrame efficiently.

In [33]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [35]:
branch_df1.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [36]:
branch_df1['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [39]:
branch_df1['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [40]:
# Are columns really different from index?

# Conceptually same (both labels), but index identifies rows and columns represent features, so they play different roles in practice.

In [42]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2   # this is a 3D data with multiindex columns

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [43]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [44]:
branch_df2['mumbai']

      avg_package  students
2019            0         0
2020            0         0
2021            0         0
2022            0         0

In [45]:
branch_df2['mumbai']['avg_package']

2019    0
2020    0
2021    0
2022    0
Name: avg_package, dtype: int64

In [46]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [48]:
branch_df2['delhi']['avg_package'].loc[2019]

np.int64(1)

In [49]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [55]:
branch_df3['delhi']['avg_package'].loc['cse'].loc[2021] # 4D data

np.int64(5)

### Stacking and Unstacking

In [58]:
branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [64]:
branch_df1.unstack()

# so the inside(level_1, year) row will become column

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [65]:
branch_df1.unstack().unstack()

# so the remaining level_0 index also became column

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [66]:
type(branch_df1.unstack().unstack())

pandas.core.series.Series

In [71]:
# stack

branch_df1.unstack().stack(future_stack=True)

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [73]:
branch_df1.unstack().stack(future_stack=True).stack(future_stack=True)

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [74]:
# Pandas is updating stack(), so use future_stack=True to avoid warnings and stay compatible.

In [75]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [76]:
branch_df2.unstack()

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    0
                     2021    0
                     2022    0
dtype: int64

In [78]:
branch_df2.stack(future_stack=True)

                  delhi  mumbai
2019 avg_package      1       0
     students         2       0
2020 avg_package      3       0
     students         4       0
2021 avg_package      5       0
     students         6       0
2022 avg_package      7       0
     students         8       0

In [80]:
branch_df2.stack(future_stack=True).stack(future_stack=True)
# this is a 3d Series

2019  avg_package  delhi     1
                   mumbai    0
      students     delhi     2
                   mumbai    0
2020  avg_package  delhi     3
                   mumbai    0
      students     delhi     4
                   mumbai    0
2021  avg_package  delhi     5
                   mumbai    0
      students     delhi     6
                   mumbai    0
2022  avg_package  delhi     7
                   mumbai    0
      students     delhi     8
                   mumbai    0
dtype: int64

In [82]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [83]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [84]:
branch_df1.unstack().unstack()

# this is a 4D series

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [90]:
type(branch_df1.unstack().unstack())

pandas.core.series.Series

In [91]:
(branch_df1.unstack().unstack()).ndim

1

In [94]:
(branch_df1.unstack().unstack()).index.nlevels

3

In [ ]:
# A Series is always 1D.
# But it can represent 4D-like data using a MultiIndex with 4 levels.

In [96]:
branch_df3.stack(future_stack=True)

                      delhi  mumbai
cse 2019 avg_package      1       0
         students         2       0
    2020 avg_package      3       0
         students         4       0
    2021 avg_package      5       0
         students         6       0
    2022 avg_package      7       0
         students         8       0
ece 2019 avg_package      9       0
         students        10       0
    2020 avg_package     11       0
         students        12       0
    2021 avg_package     13       0
         students        14       0
    2022 avg_package     15       0
         students        16       0

In [101]:
branch_df3.stack(future_stack=True).stack(future_stack=True)

cse  2019  avg_package  delhi      1
                        mumbai     0
           students     delhi      2
                        mumbai     0
     2020  avg_package  delhi      3
                        mumbai     0
           students     delhi      4
                        mumbai     0
     2021  avg_package  delhi      5
                        mumbai     0
           students     delhi      6
                        mumbai     0
     2022  avg_package  delhi      7
                        mumbai     0
           students     delhi      8
                        mumbai     0
ece  2019  avg_package  delhi      9
                        mumbai     0
           students     delhi     10
                        mumbai     0
     2020  avg_package  delhi     11
                        mumbai     0
           students     delhi     12
                        mumbai     0
     2021  avg_package  delhi     13
                        mumbai     0
           students     delhi     14
                        mumbai     0
     2022  avg_package  delhi     15
                        mumbai     0
           students     delhi     16
                        mumbai     0
dtype: int64

In [ ]:
# A Series is still 1D internally.

# The values are the actual 1D data
# The MultiIndex just adds multiple labels to each value

# So each value is still a single point, but it is identified by multiple index levels (like coordinates).

# Crux: Data stays 1D, MultiIndex just gives it multi-dimensional meaning.