In [1]:
import pandas as pd
import numpy as np

## `Q:1-5`
1. You are given three quater files, your job is to append these three files and make a single dataframe.
2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe
3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.
4. Find out items which has made most revenue in each quarter.
5. Find out avg order price of each quarter.

***Note: item_price is given as str with $ sign, in earlier task you have converted this to rupees, here too first convert item_price field in rupees.***

In [2]:
items = pd.read_csv('datasets/data/items.csv')
q1 = pd.read_csv('datasets/data/quarter-1.csv')
q2 = pd.read_csv('datasets/data/quarter-2.csv')
q3 = pd.read_csv('datasets/data/quarter-3.csv')

In [3]:
q1

      order_id  quantity  item_id  choice_description_id item_price
0            1         1        1                      1     $3.39
1            1         1        2                      2     $3.39
2            2         2        4                      3    $16.98
3            4         1        7                      6     $9.25
4            6         1        9                      8     $8.75
...        ...       ...      ...                    ...        ...
2270      1831         1       16                      0     $1.50
2271      1833         1        6                    276    $11.75
2272      1833         1        6                    904    $11.75
2273      1834         1       20                    303     $8.75
2274      1834         1       20                     30     $8.75

[2275 rows x 5 columns]

In [4]:
q2

      order_id  quantity  item_id  choice_description_id item_price
0            1         1        0                      0     $2.39
1            1         1        3                      0     $2.39
2            3         1        4                      4    $10.98
3            3         1        5                      0     $1.69
4            4         1        6                      5    $11.75
...        ...       ...      ...                    ...        ...
2342      1829         1       23                     92    $11.25
2343      1830         1       23                   1043    $11.25
2344      1832         1       10                    116     $8.75
2345      1832         1        8                      0     $4.45
2346      1834         1       20                    515    $11.25

[2347 rows x 5 columns]

In [5]:
q3

Empty DataFrame
Columns: [order_id, quantity, item_id, choice_description_id, item_price]
Index: []

In [6]:
items

    item_id                              item_name
0         0           Chips and Fresh Tomato Salsa
1         1                                   Izze
2         2                       Nantucket Nectar
3         3  Chips and Tomatillo-Green Chili Salsa
4         4                           Chicken Bowl
5         5                          Side of Chips
6         6                          Steak Burrito
7         7                       Steak Soft Tacos
8         8                    Chips and Guacamole
9         9                   Chicken Crispy Tacos
10       10                     Chicken Soft Tacos
11       11                        Chicken Burrito
12       12                            Canned Soda
13       13                       Barbacoa Burrito
14       14                       Carnitas Burrito
15       15                          Carnitas Bowl
16       16                          Bottled Water
17       17  Chips and Tomatillo Green Chili Salsa
18       18                          Barbacoa Bowl
19       19                                  Chips
20       20                     Chicken Salad Bowl
21       21                             Steak Bowl
22       22                    Barbacoa Soft Tacos
23       23                         Veggie Burrito
24       24                            Veggie Bowl
25       25                     Steak Crispy Tacos
26       26    Chips and Tomatillo Red Chili Salsa
27       27                  Barbacoa Crispy Tacos
28       28                      Veggie Salad Bowl
29       29     Chips and Roasted Chili-Corn Salsa
30       30     Chips and Roasted Chili Corn Salsa
31       31                    Carnitas Soft Tacos
32       32                          Chicken Salad
33       33                      Canned Soft Drink
34       34                       Steak Salad Bowl
35       35                      6 Pack Soft Drink
36       36    Chips and Tomatillo-Red Chili Salsa
37       37                                   Bowl
38       38                                Burrito
39       39                           Crispy Tacos
40       40                  Carnitas Crispy Tacos
41       41                            Steak Salad
42       42      Chips and Mild Fresh Tomato Salsa
43       43                      Veggie Soft Tacos
44       44                    Carnitas Salad Bowl
45       45                    Barbacoa Salad Bowl
46       46                                  Salad
47       47                    Veggie Crispy Tacos
48       48                           Veggie Salad
49       49                         Carnitas Salad

### 1. You are given three quater files, your job is to append these three files and make a single dataframe.

In [7]:

p = pd.concat([q1,q2,q3], ignore_index=True)
p

     order_id quantity item_id choice_description_id item_price
0           1        1       1                     1     $3.39
1           1        1       2                     2     $3.39
2           2        2       4                     3    $16.98
3           4        1       7                     6     $9.25
4           6        1       9                     8     $8.75
...       ...      ...     ...                   ...        ...
4617     1829        1      23                    92    $11.25
4618     1830        1      23                  1043    $11.25
4619     1832        1      10                   116     $8.75
4620     1832        1       8                     0     $4.45
4621     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

### 2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe

In [8]:
p = pd.concat([q1, q2, q3], keys=['Q-1','Q-2','Q-3'])
p

         order_id quantity item_id choice_description_id item_price
Q-1 0           1        1       1                     1     $3.39
    1           1        1       2                     2     $3.39
    2           2        2       4                     3    $16.98
    3           4        1       7                     6     $9.25
    4           6        1       9                     8     $8.75
...           ...      ...     ...                   ...        ...
Q-2 2342     1829        1      23                    92    $11.25
    2343     1830        1      23                  1043    $11.25
    2344     1832        1      10                   116     $8.75
    2345     1832        1       8                     0     $4.45
    2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [9]:
# 2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe (more accurate ans)
p = pd.concat([q1, q2, q3], keys=['Q-1','Q-2','Q-3'])
p = p.reset_index(level=0).rename(columns={'level_0': 'Quarter'})
p

     Quarter order_id quantity item_id choice_description_id item_price
0        Q-1        1        1       1                     1     $3.39
1        Q-1        1        1       2                     2     $3.39
2        Q-1        2        2       4                     3    $16.98
3        Q-1        4        1       7                     6     $9.25
4        Q-1        6        1       9                     8     $8.75
...      ...      ...      ...     ...                   ...        ...
2342     Q-2     1829        1      23                    92    $11.25
2343     Q-2     1830        1      23                  1043    $11.25
2344     Q-2     1832        1      10                   116     $8.75
2345     Q-2     1832        1       8                     0     $4.45
2346     Q-2     1834        1      20                   515    $11.25

[4622 rows x 6 columns]

### 3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.

In [11]:

most_sold_q1 = q1.merge(items, how='inner', on='item_id').groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)
most_sold_q2 = q2.merge(items, how='inner', on='item_id').groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)
most_sold_q3 = q3.merge(items, how='inner', on='item_id').groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

print('q1',most_sold_q1, '\n')
print('q2',most_sold_q2, '\n')
print('q3',most_sold_q3)

q1 item_name
Chicken Bowl    367
Name: quantity, dtype: int64

q2 item_name
Chicken Bowl    394
Name: quantity, dtype: int64

q3 Series([], Name: quantity, dtype: object)

In [12]:
# 3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.

def most_sold(df):
    return (df.merge(items, on='item_id')
              .groupby('item_name')['quantity']
              .sum()
              .sort_values(ascending=False)
              .head(1))

print('q1 most sold: ')
print(most_sold(q1), '\n')
print('q2 most sold: ')
print(most_sold(q2), '\n')
print('q3 most sold: ')
print(most_sold(q3))

q1 most sold:
item_name
Chicken Bowl    367
Name: quantity, dtype: int64

q2 most sold:
item_name
Chicken Bowl    394
Name: quantity, dtype: int64

q3 most sold:
Series([], Name: quantity, dtype: object)

### 4. Find out items which has made most revenue in each quarter.

In [13]:
q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2275 entries, 0 to 2274
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               2275 non-null   int64
 1   quantity               2275 non-null   int64
 2   item_id                2275 non-null   int64
 3   choice_description_id  2275 non-null   int64
 4   item_price             2275 non-null   object
dtypes: int64(4), object(1)
memory usage: 89.0+ KB

In [14]:
q2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2347 entries, 0 to 2346
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               2347 non-null   int64
 1   quantity               2347 non-null   int64
 2   item_id                2347 non-null   int64
 3   choice_description_id  2347 non-null   int64
 4   item_price             2347 non-null   object
dtypes: int64(4), object(1)
memory usage: 91.8+ KB

In [15]:
q3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               0 non-null      object
 1   quantity               0 non-null      object
 2   item_id                0 non-null      object
 3   choice_description_id  0 non-null      object
 4   item_price             0 non-null      object
dtypes: object(5)
memory usage: 132.0+ bytes

In [16]:
q1['item_price']

0        $3.39
1        $3.39
2       $16.98
3        $9.25
4        $8.75
         ...
2270     $1.50
2271    $11.75
2272    $11.75
2273     $8.75
2274     $8.75
Name: item_price, Length: 2275, dtype: object

In [17]:
# cleaning data(converting item_price dtype to float in rupees)
current_dollar_inr = 92
for df in [q1, q2, q3]:
    df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float) * current_dollar_inr

In [18]:
q1['item_price']

0        311.88
1        311.88
2       1562.16
3        851.00
4        805.00
         ...
2270     138.00
2271    1081.00
2272    1081.00
2273     805.00
2274     805.00
Name: item_price, Length: 2275, dtype: float64

In [19]:
q1.info()

# item_price of q1,q2,q3 is converted to float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2275 entries, 0 to 2274
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               2275 non-null   int64
 1   quantity               2275 non-null   int64
 2   item_id                2275 non-null   int64
 3   choice_description_id  2275 non-null   int64
 4   item_price             2275 non-null   float64
dtypes: float64(1), int64(4)
memory usage: 89.0 KB

In [20]:
# 4. Find out items which has made most revenue in each quarter.

# q1['revenue'] = q1['item_price'] * q1['quantity']
# q1_revenue = q1.merge(items, on='item_id').groupby('item_name')['revenue'].sum().sort_values(ascending=False)
# q1_most_revenue = q1_revenue.head(1)


# print('q1',q1_most_revenue, '\n')

In [21]:
def most_revenue(df):
    df = df.copy() 
    df['revenue'] = df['item_price'] * df['quantity']
    df_revenue = df.merge(items, on='item_id').groupby('item_name')['revenue'].sum().sort_values(ascending=False)
    df_most_revenue = df_revenue.head(1)
    return df_most_revenue


print('q1 most revenue: ')
print(most_revenue(q1), '\n')

print('q2 most revenue: ')
print(most_revenue(q2), '\n')

print('q3 most revenue: ')
print(most_revenue(q3))

q1 most revenue:
item_name
Chicken Bowl    354418.96
Name: revenue, dtype: float64

q2 most revenue:
item_name
Chicken Bowl    385687.0
Name: revenue, dtype: float64

q3 most revenue:
Series([], Name: revenue, dtype: object)

### 5. Find out avg order price of each quarter.

In [22]:
q1.head(3)

   order_id  quantity  item_id  choice_description_id  item_price
0         1         1        1                      1      311.88
1         1         1        2                      2      311.88
2         2         2        4                      3     1562.16

In [23]:
# 5. Find out avg order price of each quarter.


def avg_order_price(df):
    df = df.copy()
    df['revenue'] = df['item_price'] * df['quantity']
    df_avg_price = df['revenue'].sum() / df['order_id'].nunique()
    return df_avg_price


print('q1 avg order price: ', end='')
print(avg_order_price(q1), '\n')

print('q2 avg order price: ', end='')
print(avg_order_price(q2), '\n')

q1 avg order price: 1270.4728858131487

q2 avg order price: 1221.7441597796144

## `Q-6` From the IPL wala dataset you have to find the Purple cap holder each season.

*Note: Bowler with most no wickets in a season gets purple cap. If more than one bowler have same no of wickets in the season, one with least ecomnomy among them is purple cap holder.*

Bowler's Economy = runs-conceded per six balls

In [16]:
deliveries = pd.read_csv('datasets/data/ipl_deliveries.csv')
deliveries

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [3]:
ipl = pd.read_csv('datasets/data/IPL_Matches_2008_2022.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [4]:
new_ipl = deliveries.merge(ipl, on='ID')
new_ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,...,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,...,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,...,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,...,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,...,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,...,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [20]:
purple = new_ipl.groupby(['Season','bowler']).agg({
    'total_run': 'sum',
    'isWicketDelivery': 'sum',
    'batsman_run': 'count'
}).reset_index()


purple = purple.rename(columns={'batsman_run': 'balls'})


purple['economy'] = (purple['total_run'] / purple['balls']) * 6


purple = purple.sort_values(
    ['Season','isWicketDelivery','economy'],
    ascending=[True, False, True]
)


purple_cap = purple.groupby('Season').head(1)

purple_cap

       Season         bowler  total_run  isWicketDelivery  balls   economy
84    2007/08  Sohail Tanvir        275                24    265  6.226415
174      2009       RP Singh        430                26    382  6.753927
284   2009/10        PP Ojha        439                22    360  7.316667
447      2011     SL Malinga        393                30    397  5.939547
537      2012       M Morkel        466                30    389  7.187661
629      2013       DJ Bravo        505                34    392  7.729592
779      2014      MM Sharma        457                26    324  8.462963
847      2015       DJ Bravo        442                28    324  8.185185
938      2016        B Kumar        503                24    414  7.289855
1048     2017        B Kumar        384                28    324  7.111111
1144     2018         AJ Tye        459                28    353  7.801700
1278     2019       K Rabada        382                29    298  7.691275
1381  2020/21       K Rabada        565                32    414  8.188406
1467     2021       HV Patel        461                35    361  7.662050
1671     2022      YS Chahal        536                29    429  7.496503

## `Q-7:` Best bowler in death overs.
*Note: Have taken most no of wickets in case of tie with least economy*

Death Overs - [16-20]

## `Q-8` Batsman record season wise

Make a function which takes a input `batsman_name` and it returns a dataframe.
Columns of the data frame are - `['Season','Innings', 'TotalRuns', 'Avg', 'HighestScore','StrikeRate']`.
* In result make `Season` column as index.

* Avg - total_runs/ no of time got out. - player_out column will help.
* StrikeRate -(total_runs/ balls faced) * 100- wides are not included in batsman ball faced counts. No balls are included. -> Extra_type column will help
* Batsman Can score runs on No Balls.
* Batsman can get out on No Ball or Wides. And even while being on non-striker. Keep these things in mind before masking.

###`Q-9` Using both dataset, make a dataframe as described below

Data Frame columns-> `['PlayerOfThematch', 'BattingFigure', 'BowlingFigure']`

* BattingFigure->`<runs>/<balls>`
* BowlingFigure->`<wicket>/<runs-conceded>`

DataFrame should have one record for each match.

Say 'V Kohli' got POM award then in dataset include his batting figure of that match. Say he scored 112runs in 76 balls. And he hasn't bowled so Bowling Figure will be NaN
```
PlayerOfThematch BattingFigure BowlingFigure
V Kohli          112/76         nan  

```

## **Questions Based on Iris Dataset**

- **Sepal All:** https://docs.google.com/spreadsheets/d/e/2PACX-1vT58ekmHTwptX7Bs4QOy6YByA1HMvYTACeeIjrKhHE0Pg1K_3egewHMKMh02zN9D5-yHVXfvuaa3s5u/pub?gid=2028782809&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating this sub-dataset.
    - **Id:** Id of the records.
    - **SepalLengthCm:** Sepal length of flowers in cm
    - **SepalWidthCm:** Sepal width of flowers in cm

- **Petal All:** https://docs.google.com/spreadsheets/d/e/2PACX-1vQinLXShrOz4ExNaW1bSQVuvbbhIzJW7G0kkkD2SvqSD6STjLrQQiftgI7BGe10sBZi0CNr2_sJpQAz/pub?gid=1580010789&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating this sub-dataset.
    - **Id:** Id of the records.
    - **PetalLengthCm:** Petal length of flowers in cm
    - **PetalWidthCm:** Petal width of flowers in cm

- **Iris Virginica:** https://docs.google.com/spreadsheets/d/e/2PACX-1vSK39MwduGPHYNgw5yViezoLYCVDKMCWIHzjnt3GZNaxHPFOQLr2q6no_tyqTsOk-VfXleslfGVe9eJ/pub?gid=314231613&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

- **Iris Versicolor:** https://docs.google.com/spreadsheets/d/e/2PACX-1vTcSFgLnabqIrgIc5WlwvnbbvyyJsgZjR-0E0-4TR-5aHgv_0EP6yNWglkkls3AXM2qHCR5VYzWCoTM/pub?gid=715607857&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

- **Iris Setosa:** https://docs.google.com/spreadsheets/d/e/2PACX-1vSjqJpdgy2X_oDUUqQ0sSaFKqnnf8MYU4KgJSYgHaHmq0Wb1weMOsJXh-rICHmkLcaTkOwzMYLeh959/pub?gid=2003684803&single=true&output=csv
    - **Unnamed 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

In [28]:
import pandas as pd
sepal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT58ekmHTwptX7Bs4QOy6YByA1HMvYTACeeIjrKhHE0Pg1K_3egewHMKMh02zN9D5-yHVXfvuaa3s5u/pub?gid=2028782809&single=true&output=csv")
petal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQinLXShrOz4ExNaW1bSQVuvbbhIzJW7G0kkkD2SvqSD6STjLrQQiftgI7BGe10sBZi0CNr2_sJpQAz/pub?gid=1580010789&single=true&output=csv")

virginica = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSK39MwduGPHYNgw5yViezoLYCVDKMCWIHzjnt3GZNaxHPFOQLr2q6no_tyqTsOk-VfXleslfGVe9eJ/pub?gid=314231613&single=true&output=csv")
versicolor = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTcSFgLnabqIrgIc5WlwvnbbvyyJsgZjR-0E0-4TR-5aHgv_0EP6yNWglkkls3AXM2qHCR5VYzWCoTM/pub?gid=715607857&single=true&output=csv")
setosa = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSjqJpdgy2X_oDUUqQ0sSaFKqnnf8MYU4KgJSYgHaHmq0Wb1weMOsJXh-rICHmkLcaTkOwzMYLeh959/pub?gid=2003684803&single=true&output=csv")

### `Q-9:` Plot a bar chart of the average Sepal Length  of Virginica and average Petal length of Setosa flower.

### `Q-10:` Create the complete dataset by uisng the below datasets:
- virginica
- versicolor
- setosa
- sepal all
- petal all

This dataset should have these below column names in order:
1. Id
2. Species
3. SepalLengthCm
4. SepalWidthCm
5. PetalLengthCm
6. PetalWidthCm

Also, the dataset should be shuffled means the `Id` column should not be in increasing or decreasing order. So, make a dataset which has the shuffled Id column. You can use `DataFrame.sample()` method to shuffle.

### `Q-11:` Find out the maximum and minimum sepal width and petal width of Setosa and Versicolor. To do this:
- First create a dataset with merging the required datasets
- After that, use `groupby` to create groups based on the "Species" column.
- Then find out which are asked in this question.


The output should be like this:
```bash
Minimum Sepal width of Setosa is 2.3
Maximum Sepal width of Setosa is 4.4

**************************************************

Minimum Sepal width of Versicolor is 2.0
Maximum Sepal width of Versicolor is 3.4

**************************************************
```